AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Custom Resource Provider - Usage Example
Parameters:
  CustomResourcesFunction:
    Description: The Lambda function name of the custom resources provider. Defaults to CFNCustomResourcesFunction
    Type: String
    Default: ddc_aws_lambda_function
  BucketName:
    Description: Bucket Name
    Type: String
    Default: ddc-arbitrary-terraform-state-files
  BucketKey:
    Description: Bucket Key
    Type: String
    Default: sample_state_file.tfstate
  DesiredOutput:
    Description: Desired Output
    Type: String
    Default: 's3_bucket_arn'

Resources:
  GetS3BucketARN:
    Type: AWS::CloudFormation::CustomResource
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${CustomResourcesFunction}'
      BucketName: !Ref 'BucketName'
      BucketKey: !Ref 'BucketKey'
      DesiredOutput: !Ref 'DesiredOutput'
  
  RootRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: !GetAtt GetS3BucketARN.s3_bucket_arn
                
Outputs:
  IAMRoleARN:
    Value: !GetAtt RootRole.Arn
  LoadBalancerARN:
    Value: !GetAtt GetS3BucketARN.s3_bucket_arn
